### PR TITLE
[WIP]Implement rate limiting

### PR DESCRIPTION
**Pull request by k0nserv**
This is the skeleton for rate limiting requests on trunk without any rules applied.

I need input on which paths to limit and what limits would be appropriate for said paths

cc @orta, @alloy

### CODE REVIEW

**Comment by orta** [comment]
I think the only routes we want to rate limit are the `/api/pods/*` - [methods](https://github.com/CocoaPods/trunk.cocoapods.org/blob/master/app/controllers/api/pods_controller.rb#L12-L35). I reckon defaults should be fine here too

**Comment by k0nserv** [comment]
Okay let's start with that and see

**Comment by segiddins** [comment]
@orta anything more needed for this?

**Comment by orta** [comment]
No just all the heroic caching setup process etc

**Comment by segiddins** [comment]
@k0nserv could you rebase this? @orta it'd be awesome if you could get the heroku stuff set up, I've had to restart trunk a few times in the past month

**Comment by k0nserv** [comment]
Sure thing!

**Pull request merged**
