### PR TITLE
Transactional emails for adding/deleting/deprecating

### PR DESCRIPTION
**Pull request by orta**
Most of the dependency managers I work with now ship an 'you've done a thing' email, we should probably be doing that too. Also includes https://github.com/CocoaPods/trunk.cocoapods.org/pull/304 in the commit history ATM

### CODE REVIEW

**Comment by segiddins** [comment]
Nice! IMO itd also be good to link to the versions specification_path (iirc that's what it's called?) so it's easier for owners to verify the change looks legit

**Comment by orta** [comment]
E.g the path in the specs repo?

**Comment by segiddins** [comment]
Yeah, or even the commit on GH? then it'd be applicable for all 3 changes

**Comment by orta** [comment]
Good call, lets see how easy the commit is to get

**Pull request merged**
