### PR TITLE
[SpecificationWrapper] Handle when the tag is a number instead of a s…

### PR DESCRIPTION
**Pull request by segiddins**
…tring

Closes https://github.com/CocoaPods/cocoapods-trunk/issues/59.

Guessing this fixes https://twitter.com/gmarmas/status/717080959502393345.

### CODE REVIEW

**Comment by orta** [comment]
This makes sense to me :+1:

**Comment by alloy** [comment]
Shouldn’t this be fixed in the linter instead of accepting it?

Using a float doesn’t work when there’s more than 2 components, I’m unsure atm how floats are defined to maintain their accuracy when assigned explicitly and then converted to a string.

**Comment by segiddins** [comment]
@alloy I'm not going to get around to refactoring the lint to lint the sub-keys for sources in a long time. This was an easy fix.

**Comment by alloy** [comment]
I see, that’s fair :+1:

**Pull request merged**
