### PR TITLE
[PodsController] Only use a single database query to fetch the latest sp...

### PR DESCRIPTION
**Pull request by segiddins**
...ec url

I don't think this is much faster, but it does reduce everything down to a single query

\c @floere @kylef

### CODE REVIEW

**Comment by segiddins** [comment]
Maybe we should make this a prepared statement?

**Comment by segiddins** [comment]
@floere what do you think of this?

**Comment by floere** [comment]
Let's pull it in. Thanks! :)

**Comment by floere** [comment]
@segiddins Some more in-code comments would help a reader understand better what each piece does, so that would be a good addition.

**Comment by floere** [comment]
@segiddins I think we should merge this. It's very clean. :+1:  Feel free?

**Comment by floere** [comment]
Better late than never! Thanks! :tada:

**Pull request merged**
