### PR TITLE
[Bundle] Update cocoapods-core

### PR DESCRIPTION
**Pull request by mrackwitz**
The outdated core gem can cause an error if `requires_arc` is not present in the spec, while the spec validates locally with the latest CocoaPods release. This causes a hard-to-understand error, because it isn't properly propagated to the UI. See CocoaPods/swift#24.

### CODE REVIEW

**Comment by alloy** [comment]
What about just bumping to 0.35?

**Comment by mrackwitz** [comment]
This was supposed to happen, oversaw that it is hold back by the custom branch of nap, which is used by trunk and cause an upper-constraint on core.

**Comment by segiddins** [comment]
Any reason not to use beta 0.36 on trunk, so we can use `to_pretty_json` for specs?

**Comment by mrackwitz** [comment]
We can also update to the beta release, but I see this as a separated concern.

**Comment by orta** [comment]
This just happened.

**Pull request closed without merging**
