### PR TITLE
Update CocoaPods Core

### PR DESCRIPTION
**Pull request by orta**
So that all the linters etc are up to date.

### CODE REVIEW

**Comment by dnkoutso** [comment]
LGTM unsure for the build failure

**Comment by dnkoutso** [comment]
Maybe updating bundler caused it?

**Comment by orta** [comment]
Yeah, peiji-san is pretty mature: https://github.com/Fingertips/peiji-san no changes in 4 years

**Comment by greysteil** [comment]
Failure is definitely the Bundler version. You want to do the `gem install bundler` step in a `before_install` rather than a `before_script`, since the later gets run *after* `install`.

https://docs.travis-ci.com/user/customizing-the-build

**Comment by orta** [comment]
Ah yeah - thanks @greysteil 👍

**Comment by orta** [comment]
OK this is deployed

**Pull request merged**
