### PR TITLE
Use a 200 when a pod is deleted instead of redirecting to a non-existent resource

### PR DESCRIPTION
**Pull request by orta**
Fixes https://github.com/CocoaPods/trunk.cocoapods.org/issues/168

### CODE REVIEW

**Comment by segiddins** [comment]
How will cocoapods-trunk display this?

**Comment by orta** [comment]
good q, not too sure how to check this, let's see if I can add a test with the json on cocoapods-trunk

**Comment by orta** [comment]
I verified, the plugin expects `{ :messages => [], :data_url => string }` - so I've made it do that

**Comment by segiddins** [comment]
👌🏻

**Pull request merged**
