### PR TITLE
[PodsController] Be more verbose when the current user does not own pod

### PR DESCRIPTION
**Pull request by segiddins**
\c @orta @alloy 

Would make it easier for users to self-diagnose https://github.com/CocoaPods/CocoaPods/issues/5109.

### CODE REVIEW

**Comment by orta** [comment]
Aye, this would also reduce the amount of useless disputes we get. 

Any chance you can make it only show the first three letters of the pre-`@`? `ort...@gmail.com` - it's a security-ish hole otherwise

**Comment by alloy** [comment]
Good idea :+1:

**Comment by segiddins** [comment]
@orta I believe the full email is already visible if you do `pod trunk info POD`

**Comment by segiddins** [comment]
@orta you good with me :ship: this?

**Comment by orta** [comment]
Yes

**Pull request merged**
